### PR TITLE
Renew session silently

### PR DESCRIPTION
**Pull request by tnguyen14**
I'm trying to do this following the example from https://auth0.com/docs/quickstart/spa/react/05-token-renewal and https://auth0.com/docs/libraries/auth0js/v9#using-checksession-to-acquire-new-tokens

I'm not sure sure how to do the renewal scheduling yet. It could be done in `userMenu.js` container, or the `App.js` container, where `handleAuthentication` is currently being called. And for either, I'm not sure which method would be the right place to call it. Is it in the `render` method, or one of the lifecycle methods?

/cc @tindn

### CODE REVIEW

**Comment by tindn** [comment]
I still think renewing when a fetch call fails is still better than `setTimeout`. But `setTimeout` might be a simpler route to go. Based on the linked example, you can `setTimeout` at:

- You'll want to check expiration and set the timeout at the `App.js` constructor.
- Whenever you receive new token, so `handleAuthentication` and `renewSession`. However, since these are actions, you can't return the timeoutId back to `App.js` to clear it. So maybe return the `authResult` back to `App.js` and then check the authResult and setTimeout in `App.js`?

**Comment by tnguyen14** [comment]
> The `checkSession` method allows you to acquire a new token from Auth0 for a user who is already authenticated against Auth0 for your domain.

This seems to suggest to me that `checkSession` won't work once the session is already expired (on fetch error).

I don't think you can do set timeout in the `App` constructor, because the auth information hasn't been created yet, so you don't have the `expiresAt` property.

**Comment by tindn** [comment]
It sounds to me that `checkSession` works even if the auth token is expired. 

Another even simpler method is `setTimeout` on `App.js` every 15 minutes regardless, given a 2-hour length, you'll be safe, and it's infrequent enough to not cause any trouble. I think you can even do every 1,2, or 5 minutes.

**Comment by tnguyen14** [comment]
> It sounds to me that `checkSession` works even if the auth token is expired.

It might only if the Auth0 SSO session is still valid. https://github.com/auth0/auth0.js/blob/469bdf903cd38564e1fff10e3034d6c5b69207e4/README.md#api

**Comment by tindn** [comment]
And when does Auth0 SSO session expire?

**Comment by tnguyen14** [comment]
🤷‍♂️

**Comment by tindn** [comment]
so just do default timeouts as suggested?

**Pull request merged**
